[packages]
[[package]]
name = "busybox"
version = "1.33.1-r6"

[[package]]
name = "alpine-baselayout"
version = "3.2.0-r16"

[[package]]
name = "alpine-keys"
version = "2.4-r0"

[[package]]
name = "ca-certificates-bundle"
version = "20191127-r5"

[[package]]
name = "libretls"
version = "3.3.3p1-r2"

[[package]]
name = "ssl_client"
version = "1.33.1-r6"

[[package]]
name = "apk-tools"
version = "2.12.7-r0"

[[package]]
name = "scanelf"
version = "1.3.2-r0"

[[package]]
name = "musl-utils"
version = "1.2.2-r3"

[[package]]
name = "libc-utils"
version = "0.7.2-r3"

[[package]]
name = "libgcc"
version = "10.3.1_git20210424-r2"

[[package]]
name = "libstdc++"
version = "10.3.1_git20210424-r2"

[[package]]
name = "binutils"
version = "2.35.2-r2"

[[package]]
name = "libgomp"
version = "10.3.1_git20210424-r2"

[[package]]
name = "libatomic"
version = "10.3.1_git20210424-r2"

[[package]]
name = "libgphobos"
version = "10.3.1_git20210424-r2"

[[package]]
name = "gmp"
version = "6.2.1-r1"

[[package]]
name = "isl22"
version = "0.22-r0"

[[package]]
name = "mpfr4"
version = "4.1.0-r0"

[[package]]
name = "mpc1"
version = "1.2.1-r0"

[[package]]
name = "gcc"
version = "10.3.1_git20210424-r2"

[[package]]
name = "make"
version = "4.3-r0"

[[package]]
name = "musl"
version = "1.2.2-r5"

[[package]]
name = "libmagic"
version = "5.40-r1"

[[package]]
name = "file"
version = "5.40-r1"

[[package]]
name = "musl-dev"
version = "1.2.2-r5"

[[package]]
name = "libc-dev"
version = "0.7.2-r3"

[[package]]
name = "g++"
version = "10.3.1_git20210424-r2"

[[package]]
name = "fortify-headers"
version = "1.1-r1"

[[package]]
name = "patch"
version = "2.7.6-r7"

[[package]]
name = "build-base"
version = "0.5-r3"

[[package]]
name = "ca-certificates"
version = "20230506-r0"

[[package]]
name = "brotli-libs"
version = "1.0.9-r5"

[[package]]
name = "nghttp2-libs"
version = "1.43.0-r0"

[[package]]
name = "libcurl"
version = "8.0.1-r0"

[[package]]
name = "expat"
version = "2.5.0-r0"

[[package]]
name = "pcre2"
version = "10.36-r1"

[[package]]
name = "git"
version = "2.32.7-r0"

[[package]]
name = "libcrypto1.1"
version = "1.1.1t-r2"

[[package]]
name = "libssl1.1"
version = "1.1.1t-r2"

[[package]]
name = "zlib"
version = "1.2.12-r3"

[[package]]
name = "pkgconf"
version = "1.7.4-r1"

[[package]]
name = "openssl-dev"
version = "1.1.1t-r2"

[[package]]
name = "nghttp2-dev"
version = "1.43.0-r0"

[[package]]
name = "zlib-dev"
version = "1.2.12-r3"

[[package]]
name = "brotli-dev"
version = "1.0.9-r5"

[[package]]
name = "curl-dev"
version = "8.0.1-r0"

[[package]]
name = "mingw-w64-binutils"
version = "2.36.1-r0"

[[package]]
name = "mingw-w64-winpthreads"
version = "9.0.0-r0"

[[package]]
name = "mingw-w64-headers"
version = "9.0.0-r0"

[[package]]
name = "mingw-w64-crt"
version = "9.0.0-r0"

[[package]]
name = "mingw-w64-gcc"
version = "10.3.0-r0"

[[package]]
name = "curl"
version = "8.0.1-r0"

[[package]]
name = "oniguruma"
version = "6.9.7.1-r0"

[[package]]
name = "jq"
version = "1.6-r1"

[[package]]
name = "sudo"
version = "1.9.12_p2-r0"

[[package]]
name = "ncurses-terminfo-base"
version = "6.2_p20210612-r1"

[[package]]
name = "ncurses-libs"
version = "6.2_p20210612-r1"

[[package]]
name = "readline"
version = "8.1.0-r0"

[[package]]
name = "bash"
version = "5.1.16-r0"

[[package]]
name = "libxau"
version = "1.0.9-r0"

[[package]]
name = "libmd"
version = "1.0.3-r0"

[[package]]
name = "libbsd"
version = "0.11.3-r0"

[[package]]
name = "libxdmcp"
version = "1.1.3-r0"

[[package]]
name = "libxcb"
version = "1.14-r2"

[[package]]
name = "libx11"
version = "1.7.3.1-r0"

[[package]]
name = "libxext"
version = "1.3.4-r0"

[[package]]
name = "libxrender"
version = "0.9.10-r3"

[[package]]
name = "libbz2"
version = "1.0.8-r1"

[[package]]
name = "libpng"
version = "1.6.37-r1"

[[package]]
name = "freetype"
version = "2.10.4-r3"

[[package]]
name = "libuuid"
version = "2.37.4-r0"

[[package]]
name = "fontconfig"
version = "2.13.1-r4"

[[package]]
name = "pixman"
version = "0.40.0-r3"

[[package]]
name = "cairo"
version = "1.16.0-r5"

[[package]]
name = "libffi"
version = "3.3-r2"

[[package]]
name = "libintl"
version = "0.21-r0"

[[package]]
name = "libblkid"
version = "2.37.4-r0"

[[package]]
name = "libmount"
version = "2.37.4-r0"

[[package]]
name = "pcre"
version = "8.44-r0"

[[package]]
name = "glib"
version = "2.68.3-r0"

[[package]]
name = "cairo-gobject"
version = "1.16.0-r5"

[[package]]
name = "xz-libs"
version = "5.2.5-r1"

[[package]]
name = "libxml2"
version = "2.9.14-r2"

[[package]]
name = "shared-mime-info"
version = "2.1-r0"

[[package]]
name = "libjpeg-turbo"
version = "2.1.0-r0"

[[package]]
name = "libwebp"
version = "1.2.0-r2"

[[package]]
name = "zstd-libs"
version = "1.4.9-r1"

[[package]]
name = "tiff"
version = "4.4.0-r1"

[[package]]
name = "gdk-pixbuf"
version = "2.42.6-r1"

[[package]]
name = "libxft"
version = "2.3.3-r0"

[[package]]
name = "fribidi"
version = "1.0.10-r0"

[[package]]
name = "graphite2"
version = "1.3.14-r0"

[[package]]
name = "harfbuzz"
version = "2.8.1-r0"

[[package]]
name = "pango"
version = "1.48.5-r0"

[[package]]
name = "librsvg"
version = "2.50.4-r1"

[[package]]
name = "sqlite-libs"
version = "3.35.5-r0"

[[package]]
name = "sqlite-dev"
version = "3.35.5-r0"

[[package]]
name = "fakeroot"
version = "1.25.3-r3"

[[package]]
name = "openssl"
version = "1.1.1t-r2"

[[package]]
name = "libattr"
version = "2.5.1-r0"

[[package]]
name = "attr"
version = "2.5.1-r0"

[[package]]
name = "libacl"
version = "2.2.53-r0"

[[package]]
name = "tar"
version = "1.34-r1"

[[package]]
name = "lzip"
version = "1.22-r0"

[[package]]
name = "abuild"
version = "3.8.0_rc4-r0"

[[package]]
name = "libcap"
version = "2.50-r0"

[[package]]
name = "bubblewrap"
version = "0.4.1-r2"

[[package]]
name = "libunistring"
version = "0.9.10-r1"

[[package]]
name = "gettext-libs"
version = "0.21-r0"

[[package]]
name = "gettext"
version = "0.21-r0"

[[package]]
name = "abuild-rootbld"
version = "3.8.0_rc4-r0"

[[package]]
name = "ncurses-dev"
version = "6.2_p20210612-r1"

[[package]]
name = "libedit"
version = "20210216.3.1-r0"

[[package]]
name = "libedit-dev"
version = "20210216.3.1-r0"

[[package]]
name = "libc6-compat"
version = "1.2.2-r5"

[[package]]
name = "gdbm"
version = "1.19-r0"

[[package]]
name = "mpdecimal"
version = "2.5.1-r1"

[[package]]
name = "python3"
version = "3.9.16-r0"

[[package]]
name = "python3-dev"
version = "3.9.16-r0"

[[package]]
name = "enscript"
version = "1.6.6-r3"

[[package]]
name = "dbus-libs"
version = "1.12.24-r0"

[[package]]
name = "avahi-libs"
version = "0.8-r5"

[[package]]
name = "nettle"
version = "3.7.3-r0"

[[package]]
name = "p11-kit"
version = "0.23.22-r0"

[[package]]
name = "libtasn1"
version = "4.17.0-r1"

[[package]]
name = "gnutls"
version = "3.7.1-r2"

[[package]]
name = "cups-libs"
version = "2.3.3-r3"

[[package]]
name = "jbig2dec"
version = "0.19-r0"

[[package]]
name = "lcms2"
version = "2.12-r1"

[[package]]
name = "ghostscript"
version = "9.54.0-r2"

[[package]]
name = "libltdl"
version = "2.4.6-r7"

[[package]]
name = "imagemagick-libs"
version = "7.0.11.14-r1"

[[package]]
name = "aom-libs"
version = "1.0.0-r3"

[[package]]
name = "libde265"
version = "1.0.11-r1"

[[package]]
name = "x265-libs"
version = "3.4-r0"

[[package]]
name = "libheif"
version = "1.12.0-r0"

[[package]]
name = "imagemagick"
version = "7.0.11.14-r1"

[[package]]
name = "gdb"
version = "10.2-r0"

[[package]]
name = "lz4-libs"
version = "1.9.3-r1"

[[package]]
name = "libarchive"
version = "3.5.3-r1"

[[package]]
name = "rhash-libs"
version = "1.4.1-r0"

[[package]]
name = "libuv"
version = "1.41.0-r0"

[[package]]
name = "cmake"
version = "3.20.6-r0"

[[package]]
name = "jansson"
version = "2.13.1-r0"

[[package]]
name = "jansson-dev"
version = "2.13.1-r0"

